### ISSUE TITLE
Can't run after install?

### ISSUE THREAD

**Issue by RoelN** [ftCLI/ftCLI#1]
I'm using Python 3.9.4 in a virtual environment. After install, I can't use the `ftcli` command:

```bash
$ ftcli
Traceback (most recent call last):
  File "/Users/roel/.pyenv/versions/3.9.4/bin/ftcli", line 8, in <module>
    sys.exit(main())
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/ftcli/ftcli.py", line 32, in main
    cli()
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1209, in parse_args
    echo(ctx.get_help(), color=ctx.color)
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 570, in get_help
    return self.command.get_help(self)
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 975, in get_help
    self.format_help(ctx, formatter)
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1003, in format_help
    self.format_options(ctx, formatter)
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1137, in format_options
    self.format_commands(ctx, formatter)
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1184, in format_commands
    for subcommand in self.list_commands(ctx):
  File "/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/ftcli/ftcli.py", line 12, in list_commands
    for filename in os.listdir(plugin_folder):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/roel/.pyenv/versions/3.9.4/lib/python3.9/site-packages/ftcli/commands'
```

**Comment by ftCLI** [comment]
Hi Roel,

I'm not on Mac now, but it seems that the proble is dur to the hidden folder (.pyenv). Would you try it on another path?

**Comment by RoelN** [comment]
I usually run everything inside a virtual env, so it would probably still trip up over the `.pyenv` file is that's the cause.

Installing in development mode works, so for now I can start exploring ftCLI :-)

**Comment by ftCLI** [comment]
Ok, I close the issue.

I created a wiki page on CSS kit creation: https://github.com/ftCLI/ftCLI/wiki/How-to-create-a-CSS-kit

**Comment by alerque** [comment]
This shouldn't be closed yet, it's a bug in `setup.py`. It has nothing to do with hidden directories or virtual envs either, it's a problem without those. The setup system simply does not list all the source files that should be installed. I ran into this packaging for Arch Linux, running `python setup.py install` does not install any of the command sources.

I believe they need to be called out it setuptools or use setuptools_scm (which automatically lists files based on VCS status).

**Comment by ftCLI** [comment]
Issue reopened, thanks for the feedback. I will investigate,

**Comment by ftCLI** [comment]
- Added `include_package_data=True`in setup.py
- Added `__init__.py` in /Lib and /commands

Seems working now.

**Comment by alerque** [comment]
Yes, thank you, that does seem to have done the trick. At least for the purpose of [Arch Linux packaging](https://aur.archlinux.org/packages/ftcli) the install now includes the command files and runs fine.

**Comment by ftCLI** [comment]
Nice to hear that.

Thanks indeed for pointing out the issue.

I tested on Windows (both `pip install` and `python setup.py --root`) and works.
